In [1]:
import pandas as pd

In [ ]:
# Create a simple DataFrame  
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [24, 27, 22, 32, 29],
}
df =pd.DataFrame(data)
df

      Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22
3    David   32
4      Eva   29

In [3]:
#read
df = pd.read_csv('data.csv')
df

     Name  Age  Salary
0  Hassan   32    1000
1     Ali   21    4000
2    Reza   24    2000
3  Bahram   54    2200
4   karim   34    2000
5  Maryam   29    2800

In [4]:
df.head()

     Name  Age  Salary
0  Hassan   32    1000
1     Ali   21    4000
2    Reza   24    2000
3  Bahram   54    2200
4   karim   34    2000

In [5]:
df.describe()

             Age       Salary
count   6.000000     6.000000
mean   32.333333  2333.333333
std    11.673331  1001.332446
min    21.000000  1000.000000
25%    25.250000  2000.000000
50%    30.500000  2100.000000
75%    33.500000  2650.000000
max    54.000000  4000.000000

In [7]:
df['Name']

0    Hassan
1       Ali
2      Reza
3    Bahram
4     karim
5    Maryam
Name: Name, dtype: object

In [9]:
df.iloc[3,1]

np.int64(54)

In [12]:
#flilter
filtered_df = df[df['Age'] > 20]
filtered_df

     Name  Age  Salary
0  Hassan   32    1000
1     Ali   21    4000
2    Reza   24    2000
3  Bahram   54    2200
4   karim   34    2000
5  Maryam   29    2800

In [14]:
#sort
df_sorted = df.sort_values(by='Age', ascending=False)
df_sorted

     Name  Age  Salary
3  Bahram   54    2200
4   karim   34    2000
0  Hassan   32    1000
5  Maryam   29    2800
2    Reza   24    2000
1     Ali   21    4000

In [16]:
#subset
subset = df.loc[2:4, ['Name', 'Age']]
subset

     Name  Age
2    Reza   24
3  Bahram   54
4   karim   34

In [17]:
df_grouped =df.groupby('Salary')
df_grouped

In [18]:
df_grouped.count()

        Name  Age
Salary
1000       1    1
2000       2    2
2200       1    1
2800       1    1
4000       1    1

In [20]:
#add new column
df['Experience'] = [2, 3, 1, 5, 4,3]
df

     Name  Age  Salary  Experience
0  Hassan   32    1000           2
1     Ali   21    4000           3
2    Reza   24    2000           1
3  Bahram   54    2200           5
4   karim   34    2000           4
5  Maryam   29    2800           3

In [21]:
df.drop('Experience', axis=1, inplace=True)
df

     Name  Age  Salary
0  Hassan   32    1000
1     Ali   21    4000
2    Reza   24    2000
3  Bahram   54    2200
4   karim   34    2000
5  Maryam   29    2800

In [22]:
df.loc[len(df)] = ['Frank', 26, 60000]
df

     Name  Age  Salary
0  Hassan   32    1000
1     Ali   21    4000
2    Reza   24    2000
3  Bahram   54    2200
4   karim   34    2000
5  Maryam   29    2800
6   Frank   26   60000

In [24]:
df.isna()

    Name    Age  Salary
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4  False  False   False
5  False  False   False
6  False  False   False

In [ ]:
df.to_csv('data_updated.csv', index=False)